Repository infiduk/meta-governance-dapp, pull requests merged in 2022-06, with the labels that each got.

#19 Add react-router-dom package
  package.json
  src/index.js
Labels: enhancement

#21 Block Creation Time 코드 정리(inputerr 추가/ 이전 pr comment 내용 수정)
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#23 Feature/Block Reward Amount err 코드 추가
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#24 change image (header, footer, favicon, etc icon) && README file
  README.md
  public/favicon.ico
  public/img/explorer_footer_MAINNET.png
  public/img/explorer_footer_TESTNET.png
  public/img/github_footer.png
  public/img/logo_header_MAINNET.png
  public/img/logo_header_TESTNET.png
  public/img/metadium_footer.png
  public/img/wemix_footer.png
  public/manifest.json
  src/App.js
  src/components/Nav.js
  src/components/style/loading.png
  src/components/style/style.css
Labels: enhancement

#25 Block Reward Distribution Method err 코드 추가
  src/App.css
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#26 Change Of Eco-Fund Address 폼(UI) 화면 추가 / err 코드 추가
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#27 Change Of Maintenance Address 폼 추가
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#28 Feature/web3 add authority member
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/VotingBallots.js
  src/constants.js
  src/util.js
Labels: enhancement, invalid

#29 Feature/delete 2 form
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#30 Change of MaxPriorityFeePerGas
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#32 add voting duration component and refactor code
  src/App.js
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/index.js
  src/util.js
Labels: enhancement

#33 refactor code
  src/components/ProposalForm.js
  src/util.js
Labels: enhancement

#35 Change of GasLimit&baseFee
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#36 Feature/web3 voting duration setting
  src/App.js
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/constants.js
  src/util.js
Labels: enhancement

#37 :recylcle: refactor hex - string code
  src/components/ProposalForm.js
  src/util.js
Labels: bug, enhancement

#38 Feature/modified v1.31
  src/App.css
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/style/style.css
Labels: enhancement

#40 Feature/ GasLimit & BaseFee 오타 수정
  src/components/Forms.js
Labels: bug

#41 :sparkles: add voting proposals
  src/App.js
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/VotingBallots.js
  src/constants.js
  src/util.js
Labels: enhancement

#42 Feature / Modified v1.32
  src/App.css
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#44 :sparkles: modify maxpriorityfeepergas method
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/constants.js
  src/util.js
Labels: enhancement

#46 :sparkles: modify gas limit & basefee
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/constants.js
Labels: enhancement

#47 Feature/replace authority member
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/VotingBallots.js
  src/constants.js
Labels: enhancement

#49 Feature/block reward distribution method
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/constants.js
Labels: enhancement

#51 Feature/gaslimit basefee
  src/App.js
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/constants.js
  src/util.js
Labels: enhancement

#45 Feature/MyInfo UI 추가
  src/App.css
  src/App.js
  src/components/MyForm.js
  src/components/Myinfo.js
  src/components/Nav.js
  src/components/index.js
  src/components/style/style.css
Labels: enhancement

#52 Feature/web3 myinfo
  .DS_Store
  src/App.js
  src/components/Forms.js
  src/components/MyForm.js
  src/components/Myinfo.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/VotingBallots.js
  src/components/index.js
  src/constants.js
Labels: enhancement

#53 Hotfix/footer text
  src/App.js
  src/components/Forms.js
  src/components/Modal.js
  src/components/Nav.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/VotingBallots.js
  src/util.js
  src/web3.js
Labels: enhancement

#54 Hotfix/myinfo
  src/App.js
  src/components/Forms.js
  src/components/Nav.js
Labels: enhancement

#55 :art: Myinfo - address 입력칸 w100% 되도록 수정
  src/components/MyForm.js
Labels: enhancement

#56 :art: change footer icon
  public/favicon.ico
  public/img/explorer_footer_MAINNET.png
  public/img/explorer_footer_TESTNET.png
  public/img/wemix_footer.png
  src/App.js
Labels: enhancement

#57 :art: change header logo image
  public/img/logo_header_MAINNET.png
  public/img/logo_header_TESTNET.png
  src/components/style/style.css
Labels: enhancement

#58 Feature/ballot
  src/App.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/VotingBallots.js
  src/util.js
Labels: enhancement

#59 :fire: remove unused comment
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/style/style.css
Labels: enhancement

#60 :bug: voting issue
  src/App.js
  src/components/ProposalForm.js
Labels: bug
