Repository infiduk/meta-governance-dapp, pull requests merged in 2022-05, with the labels that each got.

#1 web3 version issue
  package.json
Labels: bug

#2 refactor code - web3.js, App.js
  src/App.js
  src/web3.js
Labels: enhancement

#3 add env variable
  .gitignore
  package.json
  src/constants.js
  src/web3.js
Labels: enhancement

#4 add gas price
  package.json
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/VotingBallots.js
  src/constants.js
  src/util.js
Labels: bug, enhancement

#5 modify comment
  src/App.js
  src/components/ProposalForm.js
  src/web3.js
Labels: documentation

#6 add network switch method
  src/web3.js
Labels: enhancement

#7 add gas limit, remove gas price
  src/components/Forms.js
  src/components/ProposalForm.js
  src/constants.js
  src/util.js
Labels: enhancement

#9 merge other form + publish
  src/App.css
  src/components/Forms.js
  src/components/ProposalForm.js
  src/components/VotingBallots.js
  src/components/style/style.css
  src/util.js
  src/web3.js
Labels: enhancement

#11 Feature/add authority member 폼(ui) 수정 - base 재설정(develop)
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#12 Feature/remove authority member 폼(ui) 수정
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#13 Feature/change of governance contract address 코드 정리
  src/components/Forms.js
Labels: enhancement

#15 Feature/voting duration setting UI 수정 및 err 관련 코드 추가
  src/App.css
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#16 modify text (meta -> wemix)
  public/index.html
  src/App.js
  src/components/Forms.js
  src/components/Modal.js
  src/components/Nav.js
  src/components/ProposalForm.js
  src/components/Voting.js
  src/components/columns.js
  src/components/style/style.css
  src/util.js
Labels: enhancement

#17 Authority Member Staking Amount 폼(UI) 수정 및 err 핸들 추가
  src/components/Forms.js
  src/components/ProposalForm.js
Labels: enhancement

#18 Add dotenv package for testnet build
  README.md
  package.json
Labels: bug, enhancement
